todoproject/todo_app/urls.py
from django.urls import path
from . import views

app_name='todo_app'
urlpatterns = [

   path('',views.add,name='add'),

   path('delete/<int:taskid>/',views.delete,name='delete'),
   path('update/<int:taskid>/',views.update,name='update'),
   path('hom/',views.TaskKistview.as_view(),name='hom'),
   path('details/<int:pk>/',views.Detailview.as_view(),name='details'),
   path('edit/<int:pk>/',views.Updateview.as_view(),name='edit'),
   path('del/<int:pk>/',views.Deleteview.as_view(),name='del'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path,include

import todo_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todo_app.urls'))
]

todoproject/todo_app/models.py
from django.db import models

# Create your models here.
class Task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.IntegerField()
    date=models.DateField(blank=True,null=True)
    def __str__(self):
        return self.name

todoproject/todo_app/forms.py
from . models import Task
from django import forms

class todo_form(forms.ModelForm):
    class Meta:
        model=Task
        fields=['name','priority','date']

todoproject/todo_app/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from . models import Task
from . forms import todo_form
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView
# Create your views here.

class Deleteview(DeleteView):
    model = Task
    template_name = 'delete.html'
    success_url = reverse_lazy('todo_app:hom')
class TaskKistview(ListView):
    model = Task
    template_name = 'home.html'
    context_object_name = 'task1'
class Detailview(DetailView):
    model = Task
    template_name = 'details.html'
    context_object_name = 'task'
class Updateview(UpdateView):
    model = Task
    template_name = 'edit.html'
    context_object_name = 'task'
    fields=['name','priority','date']
    def get_success_url(self):
        return reverse_lazy('todo_app:details',kwargs={'pk':self.object.id})
def add(request):
    task1=Task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task=Task(name=name,priority=priority,date='date')
        task.save()

    return render(request,'home.html',{'task':task1})
def update(request,taskid):
    task=Task.objects.get(id=taskid)
    fm=todo_form(request.POST or None,instance=task)
    if fm.is_valid():
        fm.save()
        return redirect('/')
    return render(request,'update.html',{'fm':fm,'task':task})


    return render(request,'home.html',{'task':task1})
def details(request):
    task=Task.objects.all()
    return render(request,'details.html',{'task':task})

def delete(request,taskid):
    task=Task.objects.get(id=taskid)
    if request.method=='POST':
        task.delete()
        return redirect('/')

    return render(request,'delete.html')

todoproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

todoproject/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    <p>Are you sure, This task is done?</p>
    <input type="submit">
</form>

{% endblock %}

todoproject/templates/details.html
{% extends 'base.html' %}
{% block content %}

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{task.name}}</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">priority</h6>
    <h5 class="card-text">This task has a priority:{{task.priority}}</h5><br>
      <h5 class="card-text">Date:{{task.date}}</h5><br>
    <a type="submit" class="btn btn-danger" href="{% url 'todo_app:delete' task.id %}">Done</a>
      <a type="submit" class="btn btn-success" href="{% url 'todo_app:update' task.id %}">Update</a>
  </div>
</div>

{% endblock %}

todoproject/templates/edit.html
{% extends 'base.html' %}
{% block content %}

<div class="card">
  <div class="card-header">
    <div class="card-title">Task update</div>
    <div class="card-body">
      <form method="POST">
  {% csrf_token %}
  {{forms.as_p}}
  <button type="submit" class="btn btn-success">Confirm</button>
</form>
    </div>
  </div>
</div>


{% endblock %}

todoproject/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1 >TODO</h1>
                </div>
            </div>
            </div>

    </div>

</div>

<div class="container">
    <div class="row" >
    <div class="col-6 col-md-6">

        <form method="post" class="p-3 shadow">
            <div class="form-group">
    <input type="text" class="form-control"  name="task" placeholder="Enter name of project"><br>

            </div>
    <div class="form-group">
    <input type="text" class="form-control" name="priority" placeholder="Enter priority"><br>

    </div>
            <div class="form-group">
    <input type="date" class="form-control" name="date" placeholder="Select the date"><br>

    </div>

<form method="POST" enctype="multipart/form-data" >
    <input type="submit" class="btn btn-success">
    {% csrf_token %}


</form>


        </form>
  <br>
    </div>
        {% for i in task %}

        <div class="col-6 col-md-6">
        <div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <h6 class="card-subtitle mb-2 text-body-secondary">priority</h6>
    <h5 class="card-text">This task has a priority:{{i.priority}}</h5><br>
      <h5 class="card-text">Date:{{i.date}}</h5><br>
    <a type="submit" class="btn btn-danger" href="{% url 'todo_app:delete' i.id %}">Done</a>
      <a type="submit" class="btn btn-success" href="{% url 'todo_app:update' i.id %}">Update</a>
  </div>

            {% endfor %}
            <br>
        </div>

        </div>
            <br>
</div>

</div>



{% endblock %}

todoproject/templates/update.html
{% extends 'base.html' %}
{% block content %}

<form method="POST">
  {% csrf_token %}
  {{fm.as_p}}
  <button type="submit">Confirm</button>
</form>

{% endblock %}